# Generated by Django 4.1.5 on 2023-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('published_datetime', models.CharField(max_length=300)),
                ('thumbnail_url', models.CharField(max_length=300)),
                ('query', models.CharField(max_length=300)),
            ],
        ),
    ]
